services:
  cli:
    container_name: cli
    image: thecodingmachine/php:8.3-v4-cli-node10
    environment:
      PHP_EXTENSION_XDEBUG: 1
      PHP_INI_XDEBUG__START_WITH_REQUEST: 'yes'
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - .:/usr/src/app:rw